name: boolean_pb_extensions
description: getBoolean's extensions for Paperback v0.7 (extensions v0.6)
version: 1.0.0
homepage: https://github.com/getBoolean/boolean_pb_extensions

publish_to: "none"

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  dart_pb_extensions_common:
    git: https://github.com/getBoolean/dart_pb_extensions_common

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
