name: boolean_pb_extensions
description: getBoolean's extensions for Paperback v0.7 (extensions v0.6)
version: 1.0.0
homepage: https://github.com/getBoolean/boolean_pb_extensions

publish_to: "none"

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  dart_pb_extensions_common:
    git: https://github.com/getBoolean/dart_pb_extensions_common

dev_dependencies:
  dpaperback_cli:
    git: https://github.com/getBoolean/dpaperback_cli
  lints: ^2.0.0
  test: ^1.16.0

paperback:
  # Required
  repository_name: Boolean's Paperback Extensions
  description: Extensions for Paperback v0.6 - v0.7, written using Dart and compiled to JavaScript

  # Optional
  no_add_to_paperback_button: false # Default: false
  # Custom logo path or url. Defaults to the Paperback logo.
  repository_logo: https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Dart-logo.png/768px-Dart-logo.png
  # Custom base url for the repository
  # The default base_url will be deducted form GITHUB_REPOSITORY environment variable.
  # base_url: 